const InfoProdutos = {
  InfoProdutos: [
    {
      id: 1,
      name: "Produto A",
      preco: "xx €",
      tipo: "tipo",
      subtipo: "subtipo",
      poluicao: "poluição",
      armazem: "armazem",
      fornecedor: "fornecedor",
    },
    {
      id: 2,
      name: "Produto B",
      preco: "xx €",
      tipo: "tipo",
      subtipo: "subtipo",
      poluicao: "poluição",
      armazem: "armazem",
      fornecedor: "fornecedor",
    },
    {
      id: 3,
      name: "Produto C",
      preco: "xx €",
      tipo: "tipo",
      subtipo: "subtipo",
      poluicao: "poluição",
      armazem: "armazem",
      fornecedor: "fornecedor",
    },
    {
      id: 4,
      name: "Produto D",
      preco: "xx €",
      tipo: "tipo",
      subtipo: "subtipo",
      poluicao: "poluição",
      armazem: "armazem",
      fornecedor: "fornecedor",
    },
    {
      id: 5,
      name: "Produto E",
      preco: "xx €",
      tipo: "tipo",
      subtipo: "subtipo",
      poluicao: "poluição",
      armazem: "armazem",
      fornecedor: "fornecedor",
    },
  ],
};
export default InfoProdutos;
